version: '3.8'

services:
  semantic-segmentation-pytorch:
    build: semantic-segmentation-pytorch
    tty: true
    environment:
      - ENVIRONMENT=beta
    volumes:
      - type: bind
        source: ../
        target: /app
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu]
    command: >
      sh -c "cd /app &&
             python test.py --imgs test_images --cfg config/ade20k-hrnetv2.yaml TEST.result output &&
             python classify.py -i test_images -o hrnetv2.csv"
